language: cpp
compiler:
  - gcc
matrix:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
        packages:
          - g++-8
          - cmake 
          - cmake-data
          - libboost1.66-all-dev
          - tk8.6-dev
          - emacs25-nox
before_script:
  - mkdir externals
  - cd externals
  - svn co --quiet http://googletest.googlecode.com/svn/trunk gtest
  - svn co --quiet http://llvm.org/svn/llvm-project/llvm/tags/RELEASE_33/final llvm
  - cd llvm/tools/
  - svn co --quiet http://llvm.org/svn/llvm-project/cfe/tags/RELEASE_33/final clang
  - cd ../../..
  - mkdir builds
  - cd builds
  - mkdir gtest-debug
  - cd gtest-debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ../../externals/gtest
  - make -j3
  - cd ..
  - mkdir llvm-release
  - cd llvm-release
  - cmake -DCMAKE_BUILD_TYPE=Release ../../externals/llvm
  - make -j3
  - cd ../..
script:
  - cd builds
  - mkdir mozart2-release
  - cd mozart2-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DGTEST_SRC_DIR=../../externals/gtest -DGTEST_BUILD_DIR=../gtest-debug -DLLVM_SRC_DIR=../../externals/llvm -DLLVM_BUILD_DIR=../llvm-release ../..
  - make -j3
