language: generic
dist: trusty
sudo: false
matrix:
  include:
  - env:
    - V=4.0
    - PREFIX=/usr/lib/llvm-4.0/lib/cmake
    - BIN=/usr/lib/llvm-4.0/bin
script:
- echo "Test Deploy"
- echo "Triggering Build"
deploy:
  provider: releases
  api_key:
    secure: MhR6fTj04IEpp3GCdV2ZmGuF87ndaYtGqcaI09KgLWhYE1lE5lMBsFdDjp1tuE+r9Jd1vtF4nMR2z+F+DIXSlCzWpu6cBeEV1xCbMhgN7LLRqC97X4wnXJNoAg0Td1kosuZPpJ6wBF428Jsu0oyhVwwAm7jF2Ag5VvD7phtfmkbRDv3g3ZDI6fsU7b0zv0t9PnspQnkM3FtBuX9ZSYjYGth7Doc+evJ0XRKDQskxHzs46/sFn8ZzxX0A9qO9iVxPIx6uey6ADuPjAecbTu6ySKiEw3YbTqEMvFMIbLQl8EhujUPXjxmyFj3tc6yOQiyedqNPVrE20i4HRvp/sSel6ujrQ4G21vTlrFZUuxQ7iBaaJjfZD3TU+8D/Wi5PSowd0E9QSbLe4Rkryej8Hsb1JB6gUIh/mI2v9ikwuB0E3m5D7Jc9UDVur1xhLzoYvDm2X5DqY2ijycYQ9a3xzpG3yyzaveofWCSQPvOOa59f+e0gH3fZ7/h5/J3yjKVUG4iheP8fyTiqjW/oRA2/9RgHXYv7Fq601kMD4Fu6kTo7uUkELr0yv/7JzQQVLQU0/U/rfE2D5jSoaJqBOcwgLnI5R0kELo7mKQr5AEzMam42YufZmEhYh9qkIFeYDg4bN7+3GXZD0lDLle8iZXxmCuvDzAzfisS1xSJ5wqtyso3g+pc=
  file: appveyor.yml
  on:
    repo: azarzadavila/mozart2
    branch: travis-release
env:
  global:
  - secure: Xc+LtQi51KG2UxzzC2+hqjVDGrmXJIceRuLmCcj4tE35EH9blShVvY/SKd+IWlFU8VT0BNhK03lUk7vnUx/CDaAlSuDrDyMyOOoINA4BGv6ee7rMtaCxOKmmVsD1sfFlHKN/VuRPWxgJOPl660/zTdqa7utWVTrZUa2Sh+v1cz/MFvwV0UIeqlLsBYPtholN5a/80k22i/G+yHbmL7usHsJj0HmnGQlMaptRDXWam5kcv0g+8lgBUWUecUNtVo5119Wdtvcf45Ex69vL3PJ4bT/osYZ86Wd9HxE/kNixc0miDMdZ9UYECMew4ymql7cDB9zpPgTMKEbk+btIidEBUMBoocZUHpppLv5wZz5J/VuL8gzZb2cICM5u1jqK4lW1q9nYL0rmSwx4wsijMqtVJ9m+zpgS5WMnNuEZ3CuBp0zPkpwAE2ikjVzhmTP8sguJ670bgxAdTz+1t6vTNTNZYt5Y+4SWRhY/dGJryJt5yvH7eE0Qjm13StK7wiL7zm67efxX3OQNJZXGP+rtMI2304tM53MHUd4sjG6GnhaEHK4zEgSCgAKQr7+lk6VOOunSVCimC9CdS5VHSE4a5DCxT1mhORq4k6CDvoWzg/YAmV630WmODG3D/6VCum7RDgZMAUoEyYuWoLB1JOZkhVW+O7bW+A/hr21QFOU+EVW0Bqk=
  - secure: GwwlFVgoLI9pnRpFfGnARXYv2MDv13zj5mmg7+0r2DPe5rN2S6fEfBk8pv7iyoYFc6GF1PeX3Z01Me8lbx9Ubwqtuxvqj0Qw19NAZPN0q3TRaABo2rfhpRD4QP9RCbdXtq+cfOvhNi/D9ULxWINPYFqBfizduJ3rNdPchU3IDrCPuhCXEka+aTXM4R5BGAk5kgle6Q5vlRX7WLffO2q+j0Zv6xRsaVuafy9KgJZJqcRchZTRDIgJzcS7cMCkPrWcY88j6bpUQbRwwhwRBMtrJQbOPSTxEKSg7cgi9s4w3leZQhOr/PdgNLoc7KPt73+Uuus0LBUzz85dEt/0fqZPIppGIW3EIIgyY0vwCXieyHLW0/epDC9HUd1mBW7G5C5GJJzM64R+sVaqRn/17Y5Bk+9SS2NJBc4CYZKRAxmRSE+ODuoGnrL/HR3aCWVPJEzAUjYGd89SLQRM6atj1/XSOSWB05lML+COYfbFNS/JURoC273RuJbOLRrTNOL5ZGkx+fmofIc4YTNn+nCi7gaiqkgUoniZHsrCrSyQr2nXL/nJq1vPvI4ZIff2aqJ85oN0s0+NaZKZ4pr2Lo5px5fdewucz2zA5ng8mRRqIzMymyQxhD3YhV1Uhr+YhMUZcAzAvJoTnsRmi7n5IZfoQAgVY98KHvMtYenYd8qAuaKzMO8=
