language: generic
dist: trusty
sudo: false
matrix:
  include:
    - before_script:
        - echo "1" > test-before.txt
    - before_script:
        - echo "2" > test-before.txt
jobs:
  include:
    - stage: check sources
      before_script:
        - echo "1" > test-before.txt
      script:
        - cat test-before.txt

    - stage: compiling with pre-generated sources
      before_script:
        - echo "2" > test-before.txt
      script:
        - cat test-before.txt
