language: generic
dist: trusty
sudo: false
env:
 - [ "V=4.0", "PREFIX=/usr/lib/llvm-4.0/lib/cmake", "BIN=/usr/lib/llvm-4.0/bin" ]
addons:
    apt:
      sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0" ]
      packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-4.0", "libclang-4.0-dev", "llvm-4.0-dev", "clang-format-4.0", "clang-tidy-4.0" ]

jobs:
  include:
    - stage: check sources
      before_script:
        - env
        - echo "1" > test-before.txt
        # Fix clang cmake dirs
        - sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang
        - sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang-4.0; fi
        - if [ $V == 4.0 ]; then  sudo -E ln -s  /usr/bin/*                /usr/lib/llvm-4.0/bin || true;         fi

      script:
        - cat test-before.txt

    - stage: compiling with pre-generated sources
      before_script:
        - env
        - echo "2" > test-before.txt
      script:
        - cat test-before.txt
