language: generic
dist: trusty
sudo: false
matrix:
  include:
    # Versions before 3.8 are not included nor whitelisted

    # Broken (uses ubuntu's version, not llvm one. {LLVM,Clang}Config.cmake are beyond redemption
    #- env: [ "V=3.8", "PREFIX=/usr/lib/llvm-3.8" ]
    #  addons:
    #    apt:
    #      sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.8" ]
    #      packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.8", "libclang-3.8-dev", "llvm-3.8-dev" ]

    # Broken: Unknown relocation 0x2a (llvm-3.9 known to be bugged on travis)
    #- env: [ "V=3.9", "PREFIX=/usr/lib/llvm-3.9/lib/cmake" ]
    #  addons:
    #    apt:
    #      sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.9" ]
    #      packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.9", "libclang-3.9-dev", "llvm-3.9-dev" ]

    # Works, with heavy fixing (see below)
    - env: [ "V=4.0", "PREFIX=/usr/lib/llvm-4.0/lib/cmake", "BIN=/usr/lib/llvm-4.0/bin" ]
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-4.0", "libclang-4.0-dev", "llvm-4.0-dev", "clang-format-4.0", "clang-tidy-4.0" ]

before_script:
  - apt list --installed
  - env
  # Fix clang cmake dirs
  - if [ $V == 3.9 ]; then  sudo -E ln -sn /usr/share/llvm-3.9/cmake /usr/lib/llvm-3.9/lib/cmake/clang;     fi

  - if [ $V == 4.0 ]; then  sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang;     fi
  - if [ $V == 4.0 ]; then  sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang-4.0; fi
  - if [ $V == 4.0 ]; then  sudo -E ln -s  /usr/bin/*                /usr/lib/llvm-4.0/bin || true;         fi

script:
  - rm -rd ./vm/vm/cached
  - rm -rd ./vm/boostenv/cached
  - export SOURCES=$(pwd) && mkdir ../build && cd ../build
  - cmake -DCMAKE_BUILD_TYPE=Release -DMOZART_BOOST_USE_STATIC_LIBS=False -DCMAKE_PROGRAM_PATH=$BIN -DCMAKE_PREFIX_PATH=$PREFIX $SOURCES
  - make dist VERBOSE=1
  - make VERBOSE=1
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  file_glob: true
  file: mozart2-*-Source.zip
  api_key:
    secure: GxwttdinweSfTeSkWu3aSp//AGT/ew4iyEUaLxh8nDeVRpAHEPBtMhgF25zoP6JLfhlEAOW7+5Gmomk1a/k+VQQWbFbod3jSSUIH/4gafEN7MVgy3Ma1NEWqViSC7IH/DDIhMzHAttznDOA2nWzoV1nyDpUydM8wvs3VK2N2wEI=
