language: cpp
compiler:
  - gcc
dist: precise
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - tk-dev              # 8.6
      - emacs               # 24
      - clang-3.8-dev       # 3.8
      - llvm-3.8-dev        # 3.8
      #- libboost-all-dev    # 1.58
      - libboost-atomic-dev
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-random-dev
      - libboost-system-dev
      - libboost-thread-dev
before_script:
  - apt list --installed
script:
  - "export SOURCES=$(pwd) && mkdir ../build && cd ../build"
  - cmake -DCMAKE_BUILD_TYPE=Release -DMOZART_BOOST_USE_STATIC_LIBS=False $SOURCES
  - make dist VERBOSE=1
  - make VERBOSE=1
