language: generic
dist: trusty
sudo: false
env:
 - [ "V=4.0", "PREFIX=/usr/lib/llvm-4.0/lib/cmake", "BIN=/usr/lib/llvm-4.0/bin" ]
jobs:
  include:
    - stage: check sources
      env: [ "V=4.0", "PREFIX=/usr/lib/llvm-4.0/lib/cmake", "BIN=/usr/lib/llvm-4.0/bin" ]
      before_script:
        - env
        - echo "1" > test-before.txt
      script:
        - cat test-before.txt

    - stage: compiling with pre-generated sources
      before_script:
        - env
        - echo "2" > test-before.txt
      script:
        - cat test-before.txt
