language: generic
dist: trusty
sudo: false
matrix:
  include:
    - custom:
        - echo "1" > test-before.txt
        - echo "script 1"
        - cat test-before.txt
    - custom:
        - echo "2" > test-before.txt
        - echo "script 2"
        - cat test-before.txt
stage: custom
