language: generic
dist: trusty
sudo: false
matrix:
  include:
    - before_script:
      - echo "1" > test-before.txt
    - script:
      - echo "script 1"
      - cat test-before.txt
    - before_script:
      - echo "2" > test-before.txt
    - script:
      - echo "script 2"
      - cat test-before.txt
