language: generic
dist: trusty
sudo: false
matrix:
  include:
    - before_script:
        - echo "1" > test-before.txt
    - before_script:
        - echo "2" > test-before.txt
jobs:
  include:
    - before_script:
       - echo "3" > test-before.txt
    - stage: script
    - script:
      - cat test-before.txt
