language: generic
dist: trusty
sudo: false
matrix:
  include:
    - custom:
      - before_script:
        - echo "1" > test-before.txt
      - script:
        - echo "script 1"
        - cat test-before.txt
    - custom:
      - before_script:
        - echo "2" > test-before.txt
      - script:
        - echo "script 2"
        - cat test-before.txt
jobs:
  include:
    - stage: before_script
    - stage: script
