language: generic
dist: trusty
sudo: false
matrix:
  include:
    - env: "V=3.6"
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.6" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.6", "libclang-3.6-dev", "llvm-3.6-dev" ]
    - env: "V=3.7"
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.7" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.7", "libclang-3.7-dev", "llvm-3.7-dev" ]
    - env: [ "V=3.8", "PREFIX=/usr/lib/llvm-3.8" ]
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.8" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.8", "libclang-3.8-dev", "llvm-3.8-dev" ]
    - env: [ "V=3.9", "PREFIX=/usr/lib/llvm-3.9/lib/cmake" ]
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.9" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-3.9", "libclang-3.9-dev", "llvm-3.9-dev" ]
    - env: [ "V=4.0", "PREFIX=/usr/lib/llvm-4.0/lib/cmake" ]
      addons:
        apt:
          sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0" ]
          packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-4.0", "libclang-4.0-dev", "llvm-4.0-dev" ]
before_script:
  - apt list --installed
  # Fix clang cmake dirs
  - if [ $V == "3.9" ]; then  sudo -E ln -sn /usr/share/llvm-3.9/cmake /usr/lib/llvm-3.9/lib/cmake/clang;     fi
  - if [ $V == "4.0" ]; then  sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang;     fi
  - if [ $V == "4.0" ]; then  sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang-4.0; fi
  - if [ $V == "4.0" ]; then  sudo -E ln -s /usr/bin/* /usr/lib/llvm-4.0/bin || true; fi

script:
  - "export SOURCES=$(pwd) && mkdir ../build && cd ../build"
  # Ok for clang >= 3.9
  - cmake -DCMAKE_BUILD_TYPE=Release -DMOZART_BOOST_USE_STATIC_LIBS=False -DCMAKE_PREFIX_PATH=$PREFIX $SOURCES
  - make dist VERBOSE=1
  - make VERBOSE=1
