#!Groovy

pipeline {

    agent {
	docker { image 'node:7-alpine' }
    }

    options { 
        checkoutToSubdirectory('mozart2')
    }

    stages {

        stage ('Test Docker') {
            steps {
		sh 'node --version'
            }
        }

    }
}
