#!Groovy

pipeline {

    agent any

    options { 
        checkoutToSubdirectory('mozart2')
    }

    stages {

        stage ('Test Docker') {
            steps {
		sh 'ls -l'
                sh 'docker help'
                sh 'docker version'
		sh 'docker info'
		sh 'docker run hello-world'
            }
        }

    }
}
